"""esquema inicial

Revision ID: b4140c57c5a0
Revises: 
Create Date: 2026-09-25 21:06:03.676663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4140c57c5a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legacy_customers',
    sa.Column('legacy_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date_raw', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at_raw', sa.String(length=50), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('legacy_id')
    )
    op.create_table('migrated_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('natural_key', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('migrated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('natural_key', name='uq_migrated_customers_natural_key')
    )
    op.create_index(op.f('ix_migrated_customers_legacy_id'), 'migrated_customers', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_migrated_customers_natural_key'), 'migrated_customers', ['natural_key'], unique=False)
    op.create_table('migration_checkpoints',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('last_legacy_id_processed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('migration_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_field', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_logs_legacy_id'), 'migration_logs', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_migration_logs_natural_key'), 'migration_logs', ['natural_key'], unique=False)
    op.create_table('retry_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=False),
    sa.Column('natural_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_queue_legacy_id'), 'retry_queue', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_retry_queue_natural_key'), 'retry_queue', ['natural_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_queue_natural_key'), table_name='retry_queue')
    op.drop_index(op.f('ix_retry_queue_legacy_id'), table_name='retry_queue')
    op.drop_table('retry_queue')
    op.drop_index(op.f('ix_migration_logs_natural_key'), table_name='migration_logs')
    op.drop_index(op.f('ix_migration_logs_legacy_id'), table_name='migration_logs')
    op.drop_table('migration_logs')
    op.drop_table('migration_checkpoints')
    op.drop_index(op.f('ix_migrated_customers_natural_key'), table_name='migrated_customers')
    op.drop_index(op.f('ix_migrated_customers_legacy_id'), table_name='migrated_customers')
    op.drop_table('migrated_customers')
    op.drop_table('legacy_customers')
    # ### end Alembic commands ###
